email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Adam Procter"
tagline: ""
description: "Follow <a href=\"https://micro.blog/adamprocter\">@adamprocter on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/adamprocter\">@adamprocter on Micro.blog</a>."
baseurl: ""
url: "https://discursive.adamprocter.co.uk"
markdown: "kramdown"
username: "adamprocter"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Adam Procter"
name: "Adam Procter"
gravatar_hash: "54d390c79764a5cc89c985c80fdd2faa"
avatar: "https://micro.blog/adamprocter/avatar.jpg"
full_name: "Adam Procter"
bio: ""
twitter_username: "adamprocter"
github_username: "adamprocter"
instagram_username: "adamprocter"
paginate: 20
paginate_path: "/page/:num/"
timezone: "WET"
site_id: "1123"
gems: ["jekyll-paginate"]